apiVersion: v1
kind: Secret
metadata:
    name: ${CLUSTER_CERT_SECRET_NAME}
    annotations:
        replicator.v1.mittwald.de/replicate-from: cert-manager/${CLUSTER_CERT_SECRET_NAME}
data: {
    tls.crt: '',
    tls.key: ''
}
type: kubernetes.io/tls