#
# TLS secret for non-HTTP services of Mailu.
# (replicated from the Cluster-level wildcard cert)
#

apiVersion: v1
kind: Secret
metadata:
    name: ${MAILU_APP_NAME}-certificates
    annotations:
        replicator.v1.mittwald.de/replicate-from: cert-manager/${CLUSTER_CERT_SECRET_NAME}
data: {
    tls.crt: '',
    tls.key: ''
}
type: kubernetes.io/tls