kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: test-local-device-pvc
spec:
    storageClassName: openebs-device
    accessModes:
    - ReadWriteOnce
    resources:
        requests:
            storage: 1G