apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
    name: ${GITEA_APP_NAME}
spec:
    secretName: ${GITEA_APP_NAME}-tls
    issuerRef:
        name: letsencrypt-http01
        kind: ClusterIssuer
    commonName: ${GITEA_FQN}
    dnsNames:
        - ${GITEA_FQN}
    acme:
        config:
            - http01:
                  ingressClass: nginx
              domains:
                  - ${GITEA_FQN}