#
# The current stable Helm template misses the proper "storageClass" attribute
# and it is not possible to properly override the "...alpha..." storageclass
# attribute, so we prepare the PVC in advance
#
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: ${NEXTCLOUD_APP_NAME}
    labels:
        app.kubernetes.io/name: ${NEXTCLOUD_APP_NAME}
        app.kubernetes.io/instance: ${NEXTCLOUD_APP_NAME}
    annotations:
        volume.beta.kubernetes.io/storage-class: ${NEXTCLOUD_STORAGE_CLASS}
spec:
    accessModes:
    - "ReadWriteOnce"
    storageClassName: ${NEXTCLOUD_STORAGE_CLASS}
    resources:
        requests:
            storage: "1Gi"
