ingress:
    enabled: false

# This is only needed
# tlsSecretName: docker-registry-tls

persistence:
    enabled: "true"
    storageClass: ${REGISTRY_STORAGE_CLASS}
    size: ${REGISTRY_PVC_SIZE}
    deleteEnabled: true

resources:
    requests:
        memory: 256Mi
        cpu: 100m
    limits:
        memory: 256Mi

podAnnotations:
    backup.velero.io/backup-volumes: "data"