apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: docker-registry
    annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/rewrite-target: /
        nginx.ingress.kubernetes.io/ssl-redirect: 'true'
        nginx.ingress.kubernetes.io/proxy-body-size: 30720m
        certmanager.k8s.io/cluster-issuer: 'letsencrypt-http01'
    labels:
        app: docker-registry
        instance: ${REGISTRY_APP_NAME}
spec:
    tls:
    -   secretName: ${REGISTRY_TLS_SECRET_NAME}
        hosts:
        - ${REGISTRY_FQN}

    rules:
    -   host: ${REGISTRY_FQN}
        http:
            paths:
            -   path: /
                pathType: Prefix
                backend:
                    service:
                        name: ${REGISTRY_APP_NAME}-docker-registry
                        port:
                            number: 5000
