# =====================
# Configuration Options
# More info for these options can be found in the docs
# https://access.crunchydata.com/documentation/postgres-operator/latest/installation/configuration/
# =====================
archive_mode: "true"
archive_timeout: "60"

#
# pgBackRest S3 Settings (SolaKube)
#
backrest_aws_s3_key: "${PGO_CLUSTER_S3_ACCESS_KEY}"
backrest_aws_s3_secret: "${PGO_CLUSTER_S3_ACCESS_KEY}"
backrest_aws_s3_bucket: "${PGO_CLUSTER_S3_BUCKET}"
backrest_aws_s3_endpoint: "${PGO_CLUSTER_S3_ENDPOINT}"
backrest_aws_s3_region: "${PGO_CLUSTER_S3_REGION}"
backrest_aws_s3_uri_style: ""
backrest_aws_s3_verify_tls: "true"

backrest_port: "2022"
badger: "false"

ccp_image_prefix: "registry.developers.crunchydata.com/crunchydata"
ccp_image_pull_secret: ""
ccp_image_pull_secret_manifest: ""
ccp_image_tag: "centos8-13.4-4.7.3"

create_rbac: "true"
crunchy_debug: "false"
db_name: ""
db_password_age_days: "0"
db_password_length: "24"
db_port: "5432"
db_replicas: "0"
db_user: "testuser"
default_instance_memory: "128Mi"
default_pgbackrest_memory: "48Mi"
default_pgbouncer_memory: "24Mi"
default_exporter_memory: "24Mi"
delete_operator_namespace: "false"
delete_watched_namespaces: "false"
disable_auto_failover: "false"
disable_fsgroup: "false"
reconcile_rbac: "true"
exporterport: "9187"
metrics: "false"
namespace: "pgo"
namespace_mode: "dynamic"
pgbadgerport: "10000"
pgo_add_os_ca_store: "false"

# Admin user settings (SolaKube)
pgo_admin_username: "admin"
pgo_admin_password: "${PGO_ADMIN_PASSWORD}"
pgo_admin_perms: "*"
pgo_admin_role_name: "pgoadmin"

pgo_apiserver_port: "8443"
pgo_apiserver_url: "https://postgres-operator"

pgo_client_cert_secret: "pgo.tls"

# We always install the PGO client container (SolaKube) so that the pgo client
# commands can be executed from within the Kubernetes cluster
pgo_client_container_install: "true"

pgo_client_install: "true"
pgo_client_version: "4.7.3"
pgo_cluster_admin: "false"
pgo_disable_eventing: "false"
pgo_disable_tls: "false"
pgo_image_prefix: "registry.developers.crunchydata.com/crunchydata"
pgo_image_pull_secret: ""
pgo_image_pull_secret_manifest: ""
pgo_image_tag: "centos8-4.7.3"

# PGO deployment name (SolaKube)
pgo_installation_name: "${SK_CLUSTER}"

pgo_noauth_routes: ""
pgo_operator_namespace: "pgo"
pgo_tls_ca_store: ""
pgo_tls_no_verify: "false"
pod_anti_affinity: "preferred"
pod_anti_affinity_pgbackrest: ""
pod_anti_affinity_pgbouncer: ""
scheduler_timeout: "3600"
service_type: "ClusterIP"
sync_replication: "false"

# Storage classes (SolaKube)
wal_storage: "${PGO_CLUSTER_WAL_STORAGE_CLASS}"
backrest_storage: "${PGO_CLUSTER_BACKREST_STORAGE_CLASS}"
backup_storage: "${PGO_CLUSTER_BACKUP_STORAGE_CLASS}"
primary_storage: "${PGO_CLUSTER_PRIMARY_STORAGE_CLASS}"
replica_storage: "${PGO_CLUSTER_REPLICA_STORAGE_CLASS}"
pgadmin_storage: "default"

storage1_name: "default"
storage1_access_mode: "ReadWriteOnce"
storage1_size: "1G"
storage1_type: "dynamic"
storage2_name: "hostpathstorage"
storage2_access_mode: "ReadWriteMany"
storage2_size: "1G"
storage2_type: "create"
storage3_name: "nfsstorage"
storage3_access_mode: "ReadWriteMany"
storage3_size: "1G"
storage3_type: "create"
storage3_supplemental_groups: "65534"
storage4_name: "nfsstoragered"
storage4_access_mode: "ReadWriteMany"
storage4_size: "1G"
storage4_match_labels: "crunchyzone=red"
storage4_type: "create"
storage4_supplemental_groups: "65534"
storage5_name: "storageos"
storage5_access_mode: "ReadWriteOnce"
storage5_size: "5Gi"
storage5_type: "dynamic"
storage5_class: "fast"
storage6_name: "primarysite"
storage6_access_mode: "ReadWriteOnce"
storage6_size: "4G"
storage6_type: "dynamic"
storage6_class: "primarysite"
storage7_name: "alternatesite"
storage7_access_mode: "ReadWriteOnce"
storage7_size: "4G"
storage7_type: "dynamic"
storage7_class: "alternatesite"
storage8_name: "gce"
storage8_access_mode: "ReadWriteOnce"
storage8_size: "300M"
storage8_type: "dynamic"
storage8_class: "standard"

# Storage config (SolaKube)
# --------------

# Rook/Ceph
storage9_name: "rook-ceph-block"
storage9_access_mode: "ReadWriteOnce"
storage9_size: "1Gi"
storage9_type: "dynamic"
storage9_class: "rook-ceph-block"

# Hetzner Cloud Volume storageclass
storage10_name: "hcloud-volumes"
storage10_access_mode: "ReadWriteOnce"
storage10_size: "1Gi"
storage10_type: "dynamic"
storage10_class: "hcloud-volumes"

# Minikube default storageclass
storage11_name: "standard"
storage11_access_mode: "ReadWriteOnce"
storage11_size: "1Gi"
storage11_type: "dynamic"
storage11_class: "standard"

# OpenEBS hostpath storageclass
storage12_name: "openebs-hostpath"
storage12_access_mode: "ReadWriteOnce"
storage12_size: "1Gi"
storage12_type: "dynamic"
storage12_class: "openebs-hostpath"
