---
apiVersion: v1
kind: ConfigMap
metadata:
    name: global-env
data:
    tx-smtp-relay-host: "[${POSTFIX_RELAY_SMTP_HOST}]:${POSTFIX_RELAY_SMTP_PORT}"
    tx-smtp-relay-myhostname: "smtp.${CLUSTER_FQN}"
    tx-smtp-relay-username: "${POSTFIX_RELAY_SMTP_USERNAME}"


---
apiVersion: v1
kind: Secret
metadata:
    name: global-env
stringData:
    tx-smtp-relay-password: "${POSTFIX_RELAY_SMTP_PASSWORD}"


---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: smtp-relay
spec:
    replicas: 1
    selector:
        matchLabels:
            app: smtp-relay
    template:
        metadata:
            labels:
                app: smtp-relay
        spec:
            containers:
            - name: smtp-relay
              image: applariat/tx-smtp-relay
              env:
              - name: TX_SMTP_RELAY_HOST
                valueFrom:
                    configMapKeyRef:
                        name: global-env
                        key: tx-smtp-relay-host
              - name: TX_SMTP_RELAY_MYHOSTNAME
                valueFrom:
                    configMapKeyRef:
                        name: global-env
                        key: tx-smtp-relay-myhostname
              - name: TX_SMTP_RELAY_USERNAME
                valueFrom:
                    configMapKeyRef:
                        name: global-env
                        key: tx-smtp-relay-username
              - name: TX_SMTP_RELAY_PASSWORD
                valueFrom:
                    secretKeyRef:
                        name: global-env
                        key: tx-smtp-relay-password
              ports:
              - containerPort: 25


---
apiVersion: v1
kind: Service
metadata:
    name: smtp
spec:
    ports:
    - port: 25
      targetPort: 25
      protocol: TCP
    selector:
        app: smtp-relay