ingress:
    enabled: false

persistence:
    enabled: true
    storageClass: ${OPENLDAP_STORAGE_CLASS}
    size: ${OPENLDAP_PVC_SIZE}

adminPassword: ${OPENLDAP_ADMIN_PASSWORD}
configPassword: ${OPENLDAP_ADMIN_PASSWORD}

podAnnotations:
    backup.velero.io/backup-volumes: "data"
